extends Node
## Boss taunt playback (autoload: BossVoiceSystem). A boss calls
## BossVoiceSystem.say(self, "tax", "intro") and this picks a random line from
## that category, plays it positionally near the boss, and enforces a
## per-boss cooldown so lines never stampede over each other.
##
## Files: src/assets/sounds/voice/boss/<boss>_<category>_<i>.mp3
## (generated by scripts/gen_boss_voices.py). Degrades silently if a file is
## missing — never blocks a fight. Ambient taunts auto-fire on a timer while a
## boss is registered as active.

const VOICE_DIR := "res://src/assets/sounds/voice/boss/"
## Minimum gap between any two lines from the same boss.
const COOLDOWN := 2.2
## Ambient taunt cadence window (seconds).
const AMBIENT_MIN := 8.0
const AMBIENT_MAX := 12.0

var _player: AudioStreamPlayer2D
var _cooldown := 0.0
var _ambient_timer := 0.0
var _active_boss: Node2D = null
var _active_boss_id := ""
## Last line index played per "boss_id:category", so the picker never plays the
## same taunt twice in a row (founder: "they keep repeating themselves"). Pure
## randi() % count repeated an N-line pool ~1/N of the time; this makes every
## consecutive line different whenever the pool has 2+ entries.
var _last_idx: Dictionary = {}

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_player = AudioStreamPlayer2D.new()
	_player.bus = "SFX"
	_player.max_distance = 2000.0
	add_child(_player)

func _process(delta: float) -> void:
	if _cooldown > 0.0:
		_cooldown -= delta
	# Ambient taunts while a boss is alive and on-screen.
	if is_instance_valid(_active_boss) and _active_boss_id != "":
		_ambient_timer -= delta
		if _ambient_timer <= 0.0:
			_ambient_timer = randf_range(AMBIENT_MIN, AMBIENT_MAX)
			say(_active_boss, _active_boss_id, "taunt")

## Register/clear the boss whose ambient taunts should fire. Call on spawn.
func set_active(boss: Node2D, boss_id: String) -> void:
	_active_boss = boss
	_active_boss_id = boss_id
	_ambient_timer = randf_range(AMBIENT_MIN, AMBIENT_MAX)

func clear_active() -> void:
	_active_boss = null
	_active_boss_id = ""

## Play a random line of `category` for `boss_id`, positioned at `source`.
## `force` bypasses the cooldown (use for intro/death/phase — story beats).
func say(source: Node2D, boss_id: String, category: String, force: bool = false) -> void:
	if not force and _cooldown > 0.0:
		return
	var count: int = BossVoiceData.COUNTS.get(boss_id, {}).get(category, 0)
	if count <= 0:
		return
	# Pick a line, avoiding an immediate repeat of the last one in this
	# category. With 2+ lines the next taunt is always different; with 1 it
	# just plays it. This is the cheap half of the "more vocabulary" fix — the
	# other half is more lines in BossVoiceData.COUNTS (+ their audio).
	var key := "%s:%s" % [boss_id, category]
	var idx := randi() % count
	if count > 1 and idx == int(_last_idx.get(key, -1)):
		idx = (idx + 1 + (randi() % (count - 1))) % count
	_last_idx[key] = idx
	var path := "%s%s_%s_%d.mp3" % [VOICE_DIR, boss_id, category, idx]
	if not ResourceLoader.exists(path):
		return
	var stream := load(path)
	if stream == null:
		return
	_player.stream = stream
	if is_instance_valid(source):
		_player.global_position = source.global_position
	# Duck music under the line (reuses AudioManager's voice ducking pattern
	# would require its player; keep it simple — SFX bus is separate from music).
	_player.play()
	_cooldown = COOLDOWN
