class_name BossVoiceData
extends RefCounted
## Per-boss taunt line inventory. The actual audio lives at
## src/assets/sounds/voice/boss/<boss>_<category>_<i>.mp3 (generated by
## scripts/gen_boss_voices.py from assets/boss-voices.json — the single source
## of the text). This file only needs the COUNT per category so the runtime
## (boss_voice_system.gd) can pick a random valid index; it never needs the
## text. Keep COUNTS in sync with boss-voices.json when lines are added.
##
## Boss ids: "tax" (Auditor / Tax Collector), "crystal" (Distributor /
## Crystalline Bureaucrat), "bandit" (Claim Jumper / Bandit).
##
## Categories: intro, taunt (ambient), mock (player took damage),
## hurt (boss took damage), phase50, phase25, death.

const COUNTS := {
	"tax": {"intro": 1, "taunt": 3, "mock": 2, "hurt": 2, "phase50": 1, "phase25": 1, "death": 1},
	"crystal": {"intro": 1, "taunt": 3, "mock": 2, "hurt": 2, "phase50": 1, "phase25": 1, "death": 1},
	"bandit": {"intro": 1, "taunt": 3, "mock": 2, "hurt": 2, "phase50": 1, "phase25": 1, "death": 1},
}

## Human-readable personality notes (documentation; not used at runtime).
const PROFILES := {
	"tax": "Nasal, bureaucratic, condescending — taxes/audits/paperwork.",
	"crystal": "Cold, robotic corporate-speak — optimizing/liquidating/ETH drainage.",
	"bandit": "Gravelly, wild, unhinged — dynamite, maniacal, 'greenhorn'.",
}
