extends Node
## Boss taunt playback (autoload: BossVoiceSystem). A boss calls
## BossVoiceSystem.say(self, "tax", "intro") and this picks a random line from
## that category, plays it positionally near the boss, and enforces a
## per-boss cooldown so lines never stampede over each other.
##
## Files: src/assets/sounds/voice/boss/<boss>_<category>_<i>.mp3
## (generated by scripts/gen_boss_voices.py). Degrades silently if a file is
## missing — never blocks a fight. Ambient taunts auto-fire on a timer while a
## boss is registered as active.

const VOICE_DIR := "res://src/assets/sounds/voice/boss/"
## Playback gain for the three antagonist voices. Founder root cause: this
## player sat at the default 0 dB while Lil Blunt's barks and the announcer
## (AudioManager.play_bark / play_voice) both run at +6 dB — so on a shared SFX
## bus the three bosses were a full 6 dB under everything else and vanished
## under gameplay noise. Pushed to +10 dB so the antagonists clearly cut
## through (6 dB HOTTER than the hero, which is what a menacing boss should be).
## Founder still reported "not loud enough" at +10 with a POSITIONAL player —
## the real thief was distance attenuation, fixed below; +12 was the top of
## the directive's requested +10..+12 band, chosen once nothing scaled it
## down any more.
##
## Founder ("Almost_Better" residual, 2026-08-18): "All the bosses are
## slightly a little too loud now." Now that distance attenuation is truly
## gone (non-positional), +12 reads as loud everywhere in the arena, not just
## far away — dropped to +9, still solidly above the hero's own +6 dB bark
## gain (a boss should out-volume Lil Blunt) and still non-positional, just
## not pinned at the top of the requested band any more.
const PLAYER_VOLUME_DB := 9.0
## Minimum gap between any two lines from the same boss.
const COOLDOWN := 2.2
## Ambient taunt cadence window (seconds).
const AMBIENT_MIN := 8.0
const AMBIENT_MAX := 12.0

## How hard the music ducks while a boss line is speaking, and how long the
## duck takes to release after the line ends. Boss VO is dialogue — it wins
## over the track, the same way AudioManager.play_voice ducks for the announcer.
const MUSIC_DUCK_DB := -14.0
const DUCK_RELEASE := 0.35

## NON-POSITIONAL on purpose. This was an AudioStreamPlayer2D with
## max_distance=2000 — a positional player attenuates with distance from the
## listener, so a boss on the far side of its own arena was scaled down to near
## nothing NO MATTER what volume_db said. Raising the gain to +10 dB alone did
## not fix the founder's "I can't hear them at all" because attenuation was
## eating it downstream. A plain AudioStreamPlayer is screen-space: the line
## plays at full authored level wherever the boss stands.
var _player: AudioStreamPlayer
var _music_bus := -1
var _music_db_normal := 0.0
var _duck_timer := 0.0
var _cooldown := 0.0
var _ambient_timer := 0.0
var _active_boss: Node2D = null
var _active_boss_id := ""
## Last line index played per "boss_id:category", so the picker never plays the
## same taunt twice in a row (founder: "they keep repeating themselves"). Pure
## randi() % count repeated an N-line pool ~1/N of the time; this makes every
## consecutive line different whenever the pool has 2+ entries.
var _last_idx: Dictionary = {}

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_player = AudioStreamPlayer.new()
	# "Voice" bus if the project defines one, else SFX. A dedicated bus lets the
	# mix treat dialogue separately from coin pings and axe hits.
	_player.bus = "Voice" if AudioServer.get_bus_index("Voice") != -1 else "SFX"
	_player.volume_db = PLAYER_VOLUME_DB  # was default 0 dB → bosses were inaudible
	add_child(_player)
	_music_bus = AudioServer.get_bus_index("Music")
	if _music_bus != -1:
		_music_db_normal = AudioServer.get_bus_volume_db(_music_bus)
	_player.finished.connect(_on_line_finished)

func _process(delta: float) -> void:
	if _cooldown > 0.0:
		_cooldown -= delta
	# Ambient taunts while a boss is alive and on-screen.
	if is_instance_valid(_active_boss) and _active_boss_id != "":
		_ambient_timer -= delta
		if _ambient_timer <= 0.0:
			_ambient_timer = randf_range(AMBIENT_MIN, AMBIENT_MAX)
			say(_active_boss, _active_boss_id, "taunt")

## Register/clear the boss whose ambient taunts should fire. Call on spawn.
func set_active(boss: Node2D, boss_id: String) -> void:
	_active_boss = boss
	_active_boss_id = boss_id
	_ambient_timer = randf_range(AMBIENT_MIN, AMBIENT_MAX)

func clear_active() -> void:
	_active_boss = null
	_active_boss_id = ""

## Play a random line of `category` for `boss_id`, positioned at `source`.
## `force` bypasses the cooldown (use for intro/death/phase — story beats).
func say(source: Node2D, boss_id: String, category: String, force: bool = false) -> void:
	if not force and _cooldown > 0.0:
		return
	var count: int = BossVoiceData.COUNTS.get(boss_id, {}).get(category, 0)
	if count <= 0:
		return
	# Pick a line, avoiding an immediate repeat of the last one in this
	# category. With 2+ lines the next taunt is always different; with 1 it
	# just plays it. This is the cheap half of the "more vocabulary" fix — the
	# other half is more lines in BossVoiceData.COUNTS (+ their audio).
	var key := "%s:%s" % [boss_id, category]
	var idx := randi() % count
	if count > 1 and idx == int(_last_idx.get(key, -1)):
		idx = (idx + 1 + (randi() % (count - 1))) % count
	_last_idx[key] = idx
	var path := "%s%s_%s_%d.mp3" % [VOICE_DIR, boss_id, category, idx]
	if not ResourceLoader.exists(path):
		return
	var stream := load(path)
	if stream == null:
		return
	_player.stream = stream
	# `source` is no longer used to place the sound (the player is deliberately
	# non-positional — see _player's declaration). It stays in the signature so
	# every existing boss call site keeps working unchanged.
	_player.play()
	_duck_music(true)
	_cooldown = COOLDOWN

## Pull the music down while a boss speaks and restore it after. Same intent as
## AudioManager.play_voice's announcer duck: dialogue should never fight the
## track. Guarded on the bus existing, and restores to the level the mix was
## actually at, not a hardcoded 0.
func _duck_music(on: bool) -> void:
	if _music_bus == -1:
		return
	if on:
		if _duck_timer <= 0.0:
			_music_db_normal = AudioServer.get_bus_volume_db(_music_bus)
		_duck_timer = 1.0
		AudioServer.set_bus_volume_db(_music_bus, _music_db_normal + MUSIC_DUCK_DB)
	else:
		_duck_timer = 0.0
		AudioServer.set_bus_volume_db(_music_bus, _music_db_normal)

func _on_line_finished() -> void:
	# Small release so back-to-back lines don't pump the music up and down.
	await get_tree().create_timer(DUCK_RELEASE).timeout
	if not _player.playing:
		_duck_music(false)
