#!/usr/bin/env python3
"""Sample points ON the inner surface of the founder's tunnel shell (skill: ep2-meshy-studio).

  python3 tools/meshy/shell_surface_points.py <shell.glb> <out.gd> [--n 70] [--seed 7]

Why: props scattered by guessing the wall position (view code: wall x = 5.5) float in mid-air
wherever the rock bulges — the first glowing-crystal pass showed yellow shards hanging in the
tunnel. Here the wall is measured from the mesh: random inward-facing faces of the side walls and
ceiling, above the cut floor. Output is a GDScript const of [x,y,z, nx,ny,nz] in the shell's
NATIVE space; the view maps them through each tile's transform, so crystals sit in the rock.
"""
import argparse
import numpy as np
import trimesh

ap = argparse.ArgumentParser()
ap.add_argument("glb"); ap.add_argument("out")
ap.add_argument("--n", type=int, default=70)
ap.add_argument("--seed", type=int, default=7)
a = ap.parse_args()
m = trimesh.load(a.glb, force="mesh")
c, n = m.triangles_center, m.face_normals
rng = np.random.default_rng(a.seed)
side = (np.abs(c[:, 0]) > 0.34) & (np.abs(c[:, 0]) < 0.62) & (n[:, 0] * np.sign(c[:, 0]) < -0.35) & (c[:, 1] > -0.30) & (c[:, 1] < 0.34)
ceil = (c[:, 1] > 0.18) & (n[:, 1] < -0.45) & (np.abs(c[:, 0]) < 0.45)
ok = np.where((side | ceil) & (np.abs(c[:, 2]) < 0.90))[0]
pick = rng.choice(ok, size=min(a.n, len(ok)), replace=False)
rows = []
for i in pick:
    p, nn = c[i], n[i] / np.linalg.norm(n[i])
    rows += [round(float(x), 4) for x in (*p, *nn)]
with open(a.out, "w") as f:
    f.write("class_name ShellCrystals\nextends RefCounted\n")
    f.write("## GENERATED by tools/meshy/shell_surface_points.py from mine_tunnel_shell.glb — do not edit.\n")
    f.write("## [x, y, z, nx, ny, nz] per point, in the shell's native space (walls + ceiling, inward normals).\n")
    f.write("const POINTS: Array = [\n")
    for k in range(0, len(rows), 6):
        f.write("\t" + ", ".join(str(v) for v in rows[k:k + 6]) + ",\n")
    f.write("]\n")
print("points:", len(rows) // 6, "side faces", int(side.sum()), "ceiling faces", int(ceil.sum()))
