// Weekly X post drafts for @smokering25 via Kimi K3 (content-engine skill).
// Usage: node backend/content_engine/social_post_drafts.js
// Output: marketing/assets/x_drafts_week_<ISO-week>.md
// HUMAN-IN-THE-LOOP: drafts only — a human posts them (X API automation is
// deliberately deferred; see docs/OPERATIONS_BUDGET.md, X API line).

import { kimi } from "./kimi_content.js";
import { writeFileSync, mkdirSync } from "node:fs";

const week = (() => {
  const d = new Date(); const t = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  t.setUTCDate(t.getUTCDate() + 4 - (t.getUTCDay() || 7));
  return `${t.getUTCFullYear()}-W${String(Math.ceil(((t - Date.UTC(t.getUTCFullYear(),0,1)) / 86400000 + 1) / 7)).padStart(2, "0")}`;
})();

const drafts = await kimi(
  "You draft X posts for @smokering25, the account of a chill crypto gaming protocol whose free browser platformer stars Lil Blunt. Voice: laid-back, funny, community-first, never shilling price.",
  "Draft 5 X posts. Topics: new leaderboard, community lore, token utility in-game, game update, invite-a-friend. Each under 280 chars, each includes @smokering25 and #SMOKE, each ends with the game link https://youngstunners88.itch.io/lil-blunt-adventure . Number them 1-5, one per line block.");

mkdirSync("marketing/assets", { recursive: true });
const out = `marketing/assets/x_drafts_week_${week}.md`;
writeFileSync(out, `# X drafts — week ${week} (@smokering25)\n\nStatus: DRAFT — human review + manual post. Generated by Kimi K3.\n\n${drafts}\n`);
console.log(`wrote ${out}`);
