class_name VoiceBank
extends RefCounted
## GENERATED by tools/ep2_voice/build_bank.py from assets/ep2-voice-bank.json — do not edit.
## category -> {gap: min seconds between two lines of the category, priority, ids: [voice ids]}
const DIR := "res://src/assets/sounds/voice/"
const CATEGORIES := {
	"boulder_smash": {"gap": 0.0, "priority": 100, "ids": ["ep2_vo_boulder_smash_1", "ep2_vo_boulder_smash_2", "ep2_vo_boulder_smash_3", "ep2_vo_boulder_smash_4", "ep2_vo_boulder_smash_5", "ep2_vo_boulder_smash_6", "ep2_vo_boulder_smash_7", "ep2_vo_boulder_smash_8", "ep2_vo_boulder_smash_9", "ep2_vo_boulder_smash_10", "ep2_vo_boulder_smash_11", "ep2_vo_boulder_smash_12"]},
	"boulder_warning": {"gap": 4.0, "priority": 60, "ids": ["ep2_vo_boulder_warning_1", "ep2_vo_boulder_warning_2", "ep2_vo_boulder_warning_3", "ep2_vo_boulder_warning_4", "ep2_vo_boulder_warning_5", "ep2_vo_boulder_warning_6", "ep2_vo_boulder_warning_7"]},
	"hit": {"gap": 0.0, "priority": 90, "ids": ["ep2_vo_hit_1", "ep2_vo_hit_2", "ep2_vo_hit_3", "ep2_vo_hit_4", "ep2_vo_hit_5", "ep2_vo_hit_6", "ep2_vo_hit_7", "ep2_vo_hit_8", "ep2_vo_hit_9", "ep2_vo_hit_10", "ep2_vo_hit_11"]},
	"hop_success": {"gap": 0.8, "priority": 80, "ids": ["ep2_vo_hop_success_1", "ep2_vo_hop_success_2", "ep2_vo_hop_success_3", "ep2_vo_hop_success_4", "ep2_vo_hop_success_5", "ep2_vo_hop_success_6", "ep2_vo_hop_success_7", "ep2_vo_hop_success_8", "ep2_vo_hop_success_9", "ep2_vo_hop_success_10", "ep2_vo_hop_success_11", "ep2_vo_hop_success_12", "ep2_vo_hop_success_13", "ep2_vo_hop_success_14", "ep2_vo_hop_success_15", "ep2_vo_hop_success_16", "ep2_vo_hop_success_17", "ep2_vo_hop_success_18"]},
	"jump_clear": {"gap": 2.5, "priority": 70, "ids": ["ep2_vo_jump_clear_1", "ep2_vo_jump_clear_2", "ep2_vo_jump_clear_3", "ep2_vo_jump_clear_4", "ep2_vo_jump_clear_5", "ep2_vo_jump_clear_6", "ep2_vo_jump_clear_7", "ep2_vo_jump_clear_8", "ep2_vo_jump_clear_9", "ep2_vo_jump_clear_10"]},
	"duck": {"gap": 3.0, "priority": 50, "ids": ["ep2_vo_duck_1", "ep2_vo_duck_2", "ep2_vo_duck_3", "ep2_vo_duck_4", "ep2_vo_duck_5", "ep2_vo_duck_6", "ep2_vo_duck_7", "ep2_vo_duck_8"]},
	"bear_down": {"gap": 1.5, "priority": 65, "ids": ["ep2_vo_bear_down_1", "ep2_vo_bear_down_2", "ep2_vo_bear_down_3", "ep2_vo_bear_down_4", "ep2_vo_bear_down_5", "ep2_vo_bear_down_6", "ep2_vo_bear_down_7", "ep2_vo_bear_down_8", "ep2_vo_bear_down_9", "ep2_vo_bear_down_10", "ep2_vo_bear_down_11", "ep2_vo_bear_down_12"]},
	"bear_sighted": {"gap": 6.0, "priority": 55, "ids": ["ep2_vo_bear_sighted_1", "ep2_vo_bear_sighted_2", "ep2_vo_bear_sighted_3", "ep2_vo_bear_sighted_4", "ep2_vo_bear_sighted_5", "ep2_vo_bear_sighted_6"]},
	"zip_catch": {"gap": 0.0, "priority": 75, "ids": ["ep2_vo_zip_catch_1", "ep2_vo_zip_catch_2", "ep2_vo_zip_catch_3", "ep2_vo_zip_catch_4", "ep2_vo_zip_catch_5", "ep2_vo_zip_catch_6", "ep2_vo_zip_catch_7", "ep2_vo_zip_catch_8", "ep2_vo_zip_catch_9"]},
	"coin_streak": {"gap": 5.0, "priority": 30, "ids": ["ep2_vo_coin_streak_1", "ep2_vo_coin_streak_2", "ep2_vo_coin_streak_3", "ep2_vo_coin_streak_4", "ep2_vo_coin_streak_5", "ep2_vo_coin_streak_6", "ep2_vo_coin_streak_7", "ep2_vo_coin_streak_8", "ep2_vo_coin_streak_9", "ep2_vo_coin_streak_10"]},
	"reload": {"gap": 3.0, "priority": 20, "ids": ["ep2_vo_reload_1", "ep2_vo_reload_2", "ep2_vo_reload_3", "ep2_vo_reload_4", "ep2_vo_reload_5", "ep2_vo_reload_6"]},
	"dry": {"gap": 3.0, "priority": 35, "ids": ["ep2_vo_dry_1", "ep2_vo_dry_2", "ep2_vo_dry_3", "ep2_vo_dry_4", "ep2_vo_dry_5"]},
	"cart_spawn": {"gap": 4.0, "priority": 25, "ids": ["ep2_vo_cart_spawn_1", "ep2_vo_cart_spawn_2", "ep2_vo_cart_spawn_3", "ep2_vo_cart_spawn_4", "ep2_vo_cart_spawn_5"]},
	"hop_blocked": {"gap": 2.0, "priority": 45, "ids": ["ep2_vo_hop_blocked_1", "ep2_vo_hop_blocked_2", "ep2_vo_hop_blocked_3", "ep2_vo_hop_blocked_4", "ep2_vo_hop_blocked_5"]},
	"run_failed": {"gap": 0.0, "priority": 110, "ids": ["ep2_vo_run_failed_1", "ep2_vo_run_failed_2", "ep2_vo_run_failed_3", "ep2_vo_run_failed_4", "ep2_vo_run_failed_5", "ep2_vo_run_failed_6", "ep2_vo_run_failed_7"]},
	"chamber_reached": {"gap": 0.0, "priority": 85, "ids": ["ep2_vo_chamber_reached_1", "ep2_vo_chamber_reached_2", "ep2_vo_chamber_reached_3", "ep2_vo_chamber_reached_4", "ep2_vo_chamber_reached_5", "ep2_vo_chamber_reached_6", "ep2_vo_chamber_reached_7"]},
	"shoot": {"gap": 7.0, "priority": 15, "ids": ["ep2_vo_shoot_1", "ep2_vo_shoot_2", "ep2_vo_shoot_3", "ep2_vo_shoot_4", "ep2_vo_shoot_5", "ep2_vo_shoot_6"]},
	"swipe": {"gap": 2.5, "priority": 42, "ids": ["ep2_vo_swipe_1", "ep2_vo_swipe_2", "ep2_vo_swipe_3", "ep2_vo_swipe_4", "ep2_vo_swipe_5"]},
	"shovel_alert": {"gap": 0.0, "priority": 62, "ids": ["ep2_vo_shovel_alert_1", "ep2_vo_shovel_alert_2", "ep2_vo_shovel_alert_3", "ep2_vo_shovel_alert_4", "ep2_vo_shovel_alert_5", "ep2_vo_shovel_alert_6"]},
	"shovel_pass": {"gap": 0.0, "priority": 58, "ids": ["ep2_vo_shovel_pass_1", "ep2_vo_shovel_pass_2", "ep2_vo_shovel_pass_3", "ep2_vo_shovel_pass_4", "ep2_vo_shovel_pass_5"]},
	"btc": {"gap": 2.5, "priority": 28, "ids": ["vo_lb_btc_1", "vo_lb_btc_2", "vo_lb_btc_3", "vo_lb_btc_4"]},
	"panic": {"gap": 0.0, "priority": 90, "ids": ["vo_lb_panic_1", "vo_lb_panic_2", "vo_lb_panic_3", "vo_lb_panic_4"]},
	"idle": {"gap": 18.0, "priority": 10, "ids": ["ep2_vo_idle_1", "ep2_vo_idle_2", "ep2_vo_idle_3", "ep2_vo_idle_4", "ep2_vo_idle_5", "ep2_vo_idle_6"]},
}
