class_name VoiceBank
extends RefCounted
## GENERATED by tools/ep2_voice/build_bank.py from assets/ep2-voice-bank.json — do not edit.
## category -> {gap: min seconds between two lines of the category, priority, ids: [voice ids]}
const DIR := "res://src/assets/sounds/voice/"
const CATEGORIES := {
	"boulder_smash": {"gap": 0.0, "priority": 100, "ids": ["ep2_vo_boulder_smash_1", "ep2_vo_boulder_smash_2", "ep2_vo_boulder_smash_3", "ep2_vo_boulder_smash_4", "ep2_vo_boulder_smash_5", "ep2_vo_boulder_smash_6", "ep2_vo_boulder_smash_7"]},
	"boulder_warning": {"gap": 4.0, "priority": 60, "ids": ["ep2_vo_boulder_warning_1", "ep2_vo_boulder_warning_2", "ep2_vo_boulder_warning_3", "ep2_vo_boulder_warning_4"]},
	"hit": {"gap": 0.0, "priority": 90, "ids": ["ep2_vo_hit_1", "ep2_vo_hit_2", "ep2_vo_hit_3", "ep2_vo_hit_4", "ep2_vo_hit_5", "ep2_vo_hit_6"]},
	"hop_success": {"gap": 0.8, "priority": 80, "ids": ["ep2_vo_hop_success_1", "ep2_vo_hop_success_2", "ep2_vo_hop_success_3", "ep2_vo_hop_success_4", "ep2_vo_hop_success_5", "ep2_vo_hop_success_6", "ep2_vo_hop_success_7", "ep2_vo_hop_success_8", "ep2_vo_hop_success_9", "ep2_vo_hop_success_10"]},
	"jump_clear": {"gap": 2.5, "priority": 70, "ids": ["ep2_vo_jump_clear_1", "ep2_vo_jump_clear_2", "ep2_vo_jump_clear_3", "ep2_vo_jump_clear_4", "ep2_vo_jump_clear_5"]},
	"duck": {"gap": 3.0, "priority": 50, "ids": ["ep2_vo_duck_1", "ep2_vo_duck_2", "ep2_vo_duck_3", "ep2_vo_duck_4"]},
	"bear_down": {"gap": 1.5, "priority": 65, "ids": ["ep2_vo_bear_down_1", "ep2_vo_bear_down_2", "ep2_vo_bear_down_3", "ep2_vo_bear_down_4", "ep2_vo_bear_down_5", "ep2_vo_bear_down_6"]},
	"bear_sighted": {"gap": 6.0, "priority": 55, "ids": ["ep2_vo_bear_sighted_1", "ep2_vo_bear_sighted_2", "ep2_vo_bear_sighted_3"]},
	"zip_catch": {"gap": 0.0, "priority": 75, "ids": ["ep2_vo_zip_catch_1", "ep2_vo_zip_catch_2", "ep2_vo_zip_catch_3", "ep2_vo_zip_catch_4"]},
	"coin_streak": {"gap": 5.0, "priority": 30, "ids": ["ep2_vo_coin_streak_1", "ep2_vo_coin_streak_2", "ep2_vo_coin_streak_3", "ep2_vo_coin_streak_4", "ep2_vo_coin_streak_5"]},
	"reload": {"gap": 3.0, "priority": 20, "ids": ["ep2_vo_reload_1", "ep2_vo_reload_2", "ep2_vo_reload_3"]},
	"dry": {"gap": 3.0, "priority": 35, "ids": ["ep2_vo_dry_1", "ep2_vo_dry_2"]},
	"cart_spawn": {"gap": 4.0, "priority": 25, "ids": ["ep2_vo_cart_spawn_1", "ep2_vo_cart_spawn_2"]},
	"hop_blocked": {"gap": 2.0, "priority": 45, "ids": ["ep2_vo_hop_blocked_1", "ep2_vo_hop_blocked_2"]},
	"run_failed": {"gap": 0.0, "priority": 110, "ids": ["ep2_vo_run_failed_1", "ep2_vo_run_failed_2", "ep2_vo_run_failed_3", "ep2_vo_run_failed_4"]},
	"chamber_reached": {"gap": 0.0, "priority": 85, "ids": ["ep2_vo_chamber_reached_1", "ep2_vo_chamber_reached_2", "ep2_vo_chamber_reached_3", "ep2_vo_chamber_reached_4"]},
}
