class_name Stage1BossDefeatCutscene
extends CanvasLayer
## Stage 1 boss-defeat cutscene: Auditor down -> GOV VAULT looted -> mining
## gear claimed -> shaft jump toward Crystal Caverns (Stage 2). Plays after
## the Auditor's own death tween (see auditor.gd::die()) and before
## victory_screen.tscn — purely an interstitial, changes nothing about the
## Web3/leaderboard flow that follows it.
##
## A real Seedance-2-generated video (docs/model-responses/2026-09-05-astra-
## stage1-defeat-cutscene.md was the shot list it was built from; the
## reference still is artifacts/founder-art/references/
## stage1_boss_defeat_cutscene_reference.jpg), encoded to Ogg Theora+Vorbis
## — the one video format Godot 4.3's web export decodes without a plugin.
## Its own embedded Vorbis audio track carries both VO lines, generated by
## ElevenLabs on the project's existing custom voices and fed to Seedance as
## audio references so the video's dialogue matches the approved script —
## no separate AudioStreamPlayer needed.
##
## The project's ONE other video use (the Smoke Lounge brand video,
## secret_realm.gd) ships muted — that was a specific founder request for
## that specific ambient asset (`volume_db = -80.0`, sitting under a
## separate music crossfade), not a codec limitation. This cutscene plays
## at normal volume; Theora+Vorbis audio decodes and plays fine on Godot
## 4.3's web export like any other Ogg Theora file.
##
## Failure-safety: if the video asset is missing (fresh checkout before
## import, or a future asset swap gone wrong), `_ready()` degrades to
## emitting `finished` immediately rather than hanging the boss-death
## sequence — this project has shipped enough freeze bugs from sequences
## that assumed an asset would always be there.

signal finished

const VIDEO := "res://src/assets/video/cutscenes/stage1_boss_defeat.ogv"

var _video_player: VideoStreamPlayer = null
var _done := false

func play() -> void:
	layer = 5  # above HUD/gameplay, below the level-transition wipe (layer 10)
	process_mode = Node.PROCESS_MODE_ALWAYS
	if not ResourceLoader.exists(VIDEO):
		_finish()
		return
	var stream: VideoStream = load(VIDEO) as VideoStream
	if stream == null:
		_finish()
		return

	var vp: Vector2 = get_viewport().get_visible_rect().size
	var src := Vector2(1280.0, 720.0)
	var ar: float = src.x / maxf(1.0, src.y)
	var h: float = vp.y
	var w: float = h * ar
	if w < vp.x:
		w = vp.x
		h = w / ar

	var vid := VideoStreamPlayer.new()
	vid.name = "BossDefeatVideo"
	vid.stream = stream
	vid.expand = true
	vid.loop = false
	vid.volume_db = 0.0  # NOT muted — the video's own dialogue is the point.
	vid.position = Vector2((vp.x - w) * 0.5, (vp.y - h) * 0.5)
	vid.size = Vector2(w, h)
	vid.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(vid)
	_video_player = vid
	vid.finished.connect(_finish)
	vid.play()

	# Hard-deadline fallback: if playback stalls (decode error, a browser
	# that silently refuses autoplay-with-sound) the boss-death sequence
	# must still complete instead of hanging forever waiting on `finished`.
	get_tree().create_timer(20.0, true, false, true).timeout.connect(_finish)

func _exit_tree() -> void:
	if is_instance_valid(_video_player):
		_video_player.stop()

func _finish() -> void:
	if _done:
		return
	_done = true
	finished.emit()
	queue_free()
