#!/usr/bin/env python3
"""assets/ep2-voice-bank.json -> audio-manifest entries + src/episode2/runner/voice_bank.gd
(+ ElevenLabs takes with --generate). Skill: ep2-voice-barks. Key from env, never printed."""
import json, subprocess, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
bank = json.loads((ROOT / "assets/ep2-voice-bank.json").read_text())
mf_path = ROOT / "assets/audio-manifest.json"
mf = json.loads(mf_path.read_text())
ids = []
have_v = {v["id"] for v in mf["voice"]}
have_s = {s["id"] for s in mf["sfx"]}
gd = ["class_name VoiceBank", "extends RefCounted",
      "## GENERATED by tools/ep2_voice/build_bank.py from assets/ep2-voice-bank.json — do not edit.",
      "## category -> {gap: min seconds between two lines of the category, priority, ids: [voice ids]}",
      "const DIR := \"res://src/assets/sounds/voice/\"", "const CATEGORIES := {"]
for cat, c in bank["categories"].items():
    cid = []
    for i, text in enumerate(c["lines"], 1):
        vid = f"ep2_vo_{cat}_{i}"
        cid.append(vid)
        if vid not in have_v:
            mf["voice"].append({"id": vid, "text": text, "voice_id": bank["voice_id"],
                                "note": f"Episode 2 runner bark [{cat}] (skill ep2-voice-barks)"})
        ids.append(vid)
    gd.append(f'\t"{cat}": {{"gap": {c["gap"]}, "priority": {c["priority"]}, "ids": {json.dumps(cid)}}},')
gd.append("}")
for s in bank["bear_sfx"]:
    if s["id"] not in have_s:
        mf["sfx"].append(s)
    ids.append(s["id"])
mf_path.write_text(json.dumps(mf, indent=2, ensure_ascii=False) + "\n")
(ROOT / "src/episode2/runner/voice_bank.gd").write_text("\n".join(gd) + "\n")
print(f"{len(ids)} ids in manifest + voice_bank.gd")
if "--generate" in sys.argv:
    sys.exit(subprocess.call([sys.executable, "scripts/generate_audio.py"], cwd=ROOT))
