#!/usr/bin/env python3
"""Draw a crisp, legible Bitcoin mark for the in-game BTC/wBTC collectibles.

Founder complaint (20th+ time): the gold BTC coin in Stage 3 reads as a blurry
yellow blob — the glyph is yellow-on-yellow at 40-48px with a heavy orange glow
behind it, so the B is unreadable at gameplay size.

Why this is drawn geometrically instead of generated by an image model: AI
image generators reliably mangle logos and letterforms, and this is a real
brand mark that has to be exact. Every shape here comes from the official
Bitcoin mark: an orange disc (#F7931A) carrying a WHITE B with two vertical
strokes through it, the whole glyph rotated 14 degrees anticlockwise.

The fix for legibility is contrast + size: white on orange (not gold on gold),
rendered at 128px and downsampled with supersampling so the strokes stay clean
at the size the game actually blits.

Usage: python3 scripts/gen_btc_logo.py
"""
from PIL import Image, ImageDraw
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPRITES = ROOT / "src" / "assets" / "sprites"

BITCOIN_ORANGE = (247, 147, 26, 255)   # #F7931A — official
RIM_DARK = (198, 111, 12, 255)         # darker rim so the disc reads on bright skies
WHITE = (255, 255, 255, 255)

SS = 8  # supersample factor — the whole reason the edges come out clean


def draw_glyph(size: int) -> Image.Image:
    """The white B-with-two-strokes, drawn upright on a transparent canvas."""
    S = size * SS
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    # Proportions as fractions of the canvas, tuned to the official mark.
    stem_x0, stem_x1 = 0.34 * S, 0.45 * S      # vertical stem of the B
    body_top, body_bot = 0.24 * S, 0.78 * S
    d.rectangle([stem_x0, body_top, stem_x1, body_bot], fill=WHITE)

    # The two bowls. Each is a thick rounded "D" built from an outer rounded
    # rect minus an inner cut, so the counter (the hole) stays open at 40px.
    def bowl(y0, y1, right):
        r = (y1 - y0) / 2.0
        d.rounded_rectangle([stem_x0, y0, right, y1], radius=r, fill=WHITE)
        # counter
        inset = 0.075 * S
        d.rounded_rectangle(
            [stem_x0 + inset * 1.6, y0 + inset, right - inset, y1 - inset],
            radius=max(1.0, r - inset), fill=(0, 0, 0, 0))

    bowl(body_top, 0.505 * S, 0.70 * S)          # upper bowl
    bowl(0.495 * S, body_bot, 0.745 * S)         # lower bowl (slightly wider)

    # Re-assert the stem over the counters so the spine stays solid.
    d.rectangle([stem_x0, body_top, stem_x1, body_bot], fill=WHITE)

    # The four vertical strokes that make it a currency symbol (two up, two down).
    sw = 0.058 * S
    # Centred over the stem and over the bowl shoulder — on the real mark the
    # strokes rise out of the letter, they don't stand beside it.
    for cx in (0.392 * S, 0.545 * S):
        d.rectangle([cx - sw / 2, 0.135 * S, cx + sw / 2, body_top + 0.02 * S], fill=WHITE)
        d.rectangle([cx - sw / 2, body_bot - 0.02 * S, cx + sw / 2, 0.865 * S], fill=WHITE)

    return img


def make(size: int) -> Image.Image:
    S = size * SS
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # Disc + rim.
    d.ellipse([0, 0, S - 1, S - 1], fill=RIM_DARK)
    inset = 0.045 * S
    d.ellipse([inset, inset, S - 1 - inset, S - 1 - inset], fill=BITCOIN_ORANGE)

    glyph = draw_glyph(size).rotate(14.0, resample=Image.BICUBIC, center=(S / 2, S / 2))
    img.alpha_composite(glyph)

    return img.resize((size, size), Image.LANCZOS)


def main() -> int:
    # Match the ORIGINAL pixel footprint exactly. The collectibles blit these
    # at their natural size, so shipping a 128px master made the coins render
    # ~3x too big on screen (caught in the first browser capture). Legibility
    # here comes from CONTRAST and clean geometry -- white glyph on official
    # orange, supersampled down -- not from more pixels.
    targets = {"sprite_item_wbtc.png": 40, "sprite_item_coin-btc.png": 48}
    for name, px in targets.items():
        out = SPRITES / name
        make(px).save(out)
        print(f"  -> {out.relative_to(ROOT)} ({px}x{px}, {out.stat().st_size}B)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
